### ISSUE TITLE
Regenerating cache

### ISSUE THREAD

**Issue by jghauser** [oncomouse/coc-bibtex#1]
First of all, thanks a lot for this very useful extension!

I'm not sure if I'm doing something wrong, but I don't seem to be able to find a way to have the list of entries updated when I change my bibtex file. That is, if I add an entry to the bibtex file, I cannot find it using `:CocList bibtex`. I'm assuming there must be a cache somewhere that isn't updated. How can I set it up such that changes to the bibtex file get picked up immediately? Thanks!

**Comment by oncomouse** [comment]
Glad you're finding the plugin useful.

I've added a function, `bibtex.reloadLibrary`, that will immediately re-run the cache (the caching system also now uses file modification time to check if the library was changing; whoops…).

You can run this using `:CocCommand bibtex.reloadLibrary`.

Let me know if that works.

**Comment by jghauser** [comment]
Great, thanks a lot! I've added a few entries and they're being picked up as soon as I try to autocomplete in Vim (I never even run `:CocCommand bibtex.reloadLibrary`). So that works very well!

The only (minor) issue is that vim locks up for a few seconds when that happens (my bibliography has ~2500 entries).
