### ISSUE TITLE
Caching BibTex File

### ISSUE THREAD

**Issue by ivanvgav** [oncomouse/coc-bibtex#3]
Hello, I have a problem when i introduce the command `:CocList bibtex` its echo `[coc.nvim] List bibtex not found`.

In my vimrc I write down the config as you put in the Readme, my bib file is in exactly the same location:

```
call coc#config('list.source.bibtex', {
  \  'files': [
  \    '~/my-library.bib'
  \  ]
  \})
```

When I go to CocList and search for the bibtex extension, after I hit enter on it its display:

`[coc.nvim] Caching BibTex File /home/ivanvg/my-library.bib, one moment...`

And nothing else, I don't know if I'm setting something wrong...

Thanks in advance

**Comment by oncomouse** [comment]
I'm not sure what's causing your problem, but I have a potentially stupid-sounding question that may help determine what's going on: Does the "Caching BibTex FIle" message eventually go away? When it does, can you use `:CocList bibtex`?

The caching process takes a very long time because the package used to generate the citation objects the first time is incredibly slow. If your .bib file is really big, it can take a couple of minutes to index. If it's not that, I can start trying to figure out if there's anything else going on.

**Comment by ivanvgav** [comment]
The "Caching BibTex File" doesn't go away immediately. The option to press enter or run any command is available but it never cached the file. My bib file is not large, maybe less than 40 entries. I can not use `:CocList bibtex` it only echoes `[coc.nvim] List bibtex not found`.

I've started to use fzf-bibtex rather than this extensions because the time is stepping upon me regarding deadlines, nevertheless I would like to solve the problem.

**Comment by naveedpash** [comment]
Any progress on this? I have the same issue.

**Comment by oncomouse** [comment]
I'm not sure what could be causing this, as I'm not seeing this error. Could either of you share what OS, editor version, and version of CoC your using? I'll see if I can reproduce.

**Comment by oncomouse** [comment]
I think the issue was caused by the way cache files were created. Specifically, I wasn't using Coc.nvim's mechanism to automatically generate a data location for extensions. Version 1.2.7 **should** fix this issue.

Let me know if it doesn't.

**Comment by oncomouse** [comment]
Ok, so I was finally able to reproduce the part of this error where the extension wasn't loaded (I _hope_ the part where caching never finishes is fixed). One of my machines had a plugin loaded that was changing `filetype` in Vim. Right now, this extension only loads for markdown, pandoc, and latex files. If you are using other filetypes, I can add them or if there are others that should be supported.

**Comment by gongxiao** [comment]
Please support filetype of 'tex', thanks.

**Comment by oncomouse** [comment]
Done! I just published the new version to NPM, so `:CocUpdate` should grab it.

**Comment by gongxiao** [comment]
@oncomouse Great!

**Comment by VolkovIlia** [comment]
Try to use your plugin, but it works only with .tex and .pd files. So I always use .md, .wiki, .rmd and etc. filetypes. Can you make tutorial how to add *.filtype* to coc-settings.json to make your plugin works in readme file. Thanks.

**Comment by oncomouse** [comment]
@VolkovIlia I added an explanation to the Readme file. I also pushed a new version to NPM that should activate in any filetype rather than just Markdown and TeX, so it should work with `.wiki` files, etc.

**Comment by VolkovIlia** [comment]
The same problem: endless "Updating cache", then `CocList bibtex`  not found. It does not work for my Zotero (better-bibtex) generated file, but works fine if I use bibfile with few documents.

My bib file here:
[Library.txt](https://github.com/oncomouse/coc-bibtex/files/5704401/Library.txt)

**Comment by oncomouse** [comment]
@VolkovIlia Thank you for providing your library. It was crucial in figuring out the problem.

It turns out `coc-bibtex` was depending on an outdated citation processing library that didn't correctly deal with citation abstracts containing LaTeX math symbols.

So, I updated to the most recent version of that library and your library is now loading for me.

**Comment by oncomouse** [comment]
And to everyone else who's commented on this issues, the problem with various filetypes should now be solved. Setting `coc.source.bibtex.filetypes` to the filetypes you want to use with `coc-bibtex` will now activate both the list and the completion interface and should turn off `coc-bibtex` in unneeded filetypes.
