### ISSUE TITLE
invalid escape character in string

### ISSUE THREAD

**Issue by Freed-Wu** [oncomouse/coc-bibtex#7]
```{.json}
	"list": {
		"source": {
			"bibtex": {
				"citation": {
					"before": "\cite{",
					"after": "\}"
				}
			}
		}
	},

```
will return this error in the line where `\` exists.
thanks!

**Comment by CantoroMC** [comment]
i encounter the same problem
```json
	"list.source.bibtex.citation": {
		"before": "\\cite{",
		"after": "}"
	},
```
Should be good, even if i m no expert.
In addition i' ve found the same problem of the previous issue, CocList bibtex is not loaded and does not appear even with CocInfo

**Comment by Freed-Wu** [comment]
emmm, it can not work.

i put a main.bib, main.tex, main.md in `~`. and config it 
```{.json}
	"list": {
		"source": {
			"bibtex": {
				"files": [
					"*.bib"
				],
				"citation": {
					"before": "\\cite{",
					"after": "}"
				}
			}
		}
	},
```

![image](https://user-images.githubusercontent.com/32936898/92688582-26bc9000-f370-11ea-9cc4-42a9dba799b9.png)
![image](https://user-images.githubusercontent.com/32936898/92688614-3c31ba00-f370-11ea-8d8f-20cdf265edf7.png)

markdown can work but latex cannot work.

**Comment by oncomouse** [comment]
@CantoroMC is correct, those settings due fix the formatting of citations selected from `CocList bibtex`.

The problem @Freed-Wu identified is with completion, which is governed by different settings. CoC, as far as I understand it, is not set up to trigger completion from a string such as `\cite{`. I'll have to do some digging in Coc.nvim's code to see if there's a way to implement (I'm sure there is). Right now the relevant setting is `coc.source.bibtex.triggerCharacters`, which controls completion source triggering and is set to `@` by default.

A quick (and highly not recommended) solution would be to set `coc.source.bibtex.triggerCharacters` to `{`, but then it will trigger citation look-up on *every* LaTeX command.

I'm going to look more into this.

**Comment by oncomouse** [comment]
Ok, it turns out this was easy to fix. The README is updated describing how to trigger completion for LaTeX files. 1.2.11 has the fix.
